# Use postgres/example user/password credentials
version: '3.1'

services:

  dbservice:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: RZj4bqi4JsDsm7nPla8I9XymHqx6oZrd
      POSTGRES_DB: dbtpama
    volumes:
      - ./posgresdb:/var/lib/postgresql/data

  app:
    image: ddsdeploy
    restart: always
    ports:
      - 8080:8080
    environment:
      hibernate.hbm2ddl.auto: create
      javax.persistence.jdbc.driver: org.postgresql.Driver
      javax.persistence.jdbc.password: RZj4bqi4JsDsm7nPla8I9XymHqx6oZrd
      javax.persistence.jdbc.url: jdbc:postgres://dpg-cll2k16aov6s73f1ne0g-a.oregon-postgres.render.com/dbtpama
      javax.persistence.jdbc.user: dbtpamama_user
    depends_on:
      - dbservice
